export const atlassianSupportLanguageList = [
  "actionscript",
  "ada",
  "applescript",
  "bash",
  "c",
  "c#",
  "c++",
  "cpp",
  "css",
  "erlang",
  "go",
  "groovy",
  "haskell",
  "html",
  "java",
  "javascript",
  "js",
  "json",
  "lua",
  "none",
  "nyan",
  "objc",
  "perl",
  "php",
  "python",
  "r",
  "rainbow",
  "ruby",
  "scala",
  "sh",
  "sql",
  "swift",
  "visualbasic",
  "xml",
  "yaml"
];

// See also: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
export const markdownToWikiMarkupLanguageMapping = {
  "actionscript 3": "actionscript",
  actionscript3: "actionscript",
  as3: "actionscript",
  ada95: "ada",
  ada2005: "ada",
  osascript: "applescript",
  zsh: "bash",
  csharp: "c#",
  sass: "css",
  scss: "css",
  golang: "go",
  htm: "html",
  node: "javascript",
  "obj-c": "objc",
  objectivec: "objc",
  cperl: "perl",
  inc: "php",
  rusthon: "python",
  python3: "python",
  rscript: "r",
  splus: "r",
  jruby: "ruby",
  macruby: "ruby",
  rake: "ruby",
  rb: "ruby",
  rbx: "ruby",
  shell: "sh",
  vb: "visualbasic",
  vbnet: "visualbasic",
  "vb.net": "visualbasic",
  rss: "xml",
  xsd: "xml",
  wsdl: "xml",
  yml: "yaml"
};
